name: CI Full Run
on:
  pull_request:
    branches:
      - main
      - grok/*/*
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          exec 2>&1; set -e -o xtrace
          ./docker-buildx-cache --help
